INFO  | 04/14/2020 06:54:18 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-14-18-54-17_14824\log_exp_14824.txt
INFO  | 04/14/2020 06:54:18 PM | File run_exp.py           | Line 27    | Exp instance id = 14824
INFO  | 04/14/2020 06:54:18 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/14/2020 06:54:18 PM | File run_exp.py           | Line 29    | Config =
INFO  | 04/14/2020 06:54:18 PM | File gran_runner.py       | Line 139   | Train/val/test = 8/2/2
INFO  | 04/14/2020 06:54:18 PM | File gran_runner.py       | Line 152   | No Edges vs. Edges in training set = 120.54326923076923
ERROR | 04/14/2020 06:54:21 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 40, in main
    runner.test()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 326, in test
    A_tmp, node_pos = model(input_dict)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 502, in forward
    A, node_pos = self._sampling(batch_size)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 397, in _sampling
    node_pos[:,:,ii:jj] = pos[:,ii:jj,:].view(20, 2, -1)
RuntimeError: shape '[20, 2, -1]' is invalid for input of size 4

