INFO  | 04/14/2020 05:27:08 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-14-17-27-08_18020\log_exp_18020.txt
INFO  | 04/14/2020 05:27:08 PM | File run_exp.py           | Line 27    | Exp instance id = 18020
INFO  | 04/14/2020 05:27:08 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/14/2020 05:27:08 PM | File run_exp.py           | Line 29    | Config =
INFO  | 04/14/2020 05:27:09 PM | File gran_runner.py       | Line 139   | Train/val/test = 8/2/2
INFO  | 04/14/2020 05:27:09 PM | File gran_runner.py       | Line 152   | No Edges vs. Edges in training set = 457.7769679300292
ERROR | 04/14/2020 05:27:09 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 38, in main
    runner.train()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 176, in train
    train_dataset = eval(self.dataset_conf.loader_name)(self.config, self.graphs_train, tag='train')
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\dataset\gran_data.py", line 50, in __init__
    data = self._get_graph_data(G)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\dataset\gran_data.py", line 116, in _get_graph_data
    num_core = nx.core_number(G)
  File "<C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\decorator.py:decorator-gen-226>", line 2, in core_number
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\networkx\utils\decorators.py", line 82, in _not_implemented_for
    return not_implement_for_func(*args, **kwargs)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\networkx\algorithms\core.py", line 83, in core_number
    raise NetworkXError(msg)
networkx.exception.NetworkXError: Input graph has self loops which is not permitted; Consider using G.remove_edges_from(nx.selfloop_edges(G)).

