INFO  | 04/01/2020 04:26:00 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-01-16-26-00_3684\log_exp_3684.txt
INFO  | 04/01/2020 04:26:00 PM | File run_exp.py           | Line 27    | Exp instance id = 3684
INFO  | 04/01/2020 04:26:00 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/01/2020 04:26:00 PM | File run_exp.py           | Line 29    | Config =
INFO  | 04/01/2020 04:26:00 PM | File gran_runner.py       | Line 124   | Train/val/test = 8/2/2
INFO  | 04/01/2020 04:26:00 PM | File gran_runner.py       | Line 137   | No Edges vs. Edges in training set = 2.0
ERROR | 04/01/2020 04:26:06 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 40, in main
    runner.test()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 310, in test
    A_tmp = model(input_dict)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 485, in forward
    A = self._sampling(batch_size)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 343, in _sampling
    tmp_node_pos = [torch.cat((node_pos[bb,:, :ii], node_pos[bb,:,ii]), dim=0) for bb in range(B)]
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 343, in <listcomp>
    tmp_node_pos = [torch.cat((node_pos[bb,:, :ii], node_pos[bb,:,ii]), dim=0) for bb in range(B)]
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at C:/w/1/s/tmp_conda_3.7_055457/conda/conda-bld/pytorch_1565416617654/work/aten/src\THC/generic/THCTensorMath.cu:62

