INFO  | 04/09/2020 09:54:55 AM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-09-09-54-55_7992\log_exp_7992.txt
INFO  | 04/09/2020 09:54:55 AM | File run_exp.py           | Line 27    | Exp instance id = 7992
INFO  | 04/09/2020 09:54:55 AM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/09/2020 09:54:55 AM | File run_exp.py           | Line 29    | Config =
INFO  | 04/09/2020 09:54:56 AM | File gran_runner.py       | Line 124   | Train/val/test = 8/2/2
INFO  | 04/09/2020 09:54:56 AM | File gran_runner.py       | Line 137   | No Edges vs. Edges in training set = 2.0
ERROR | 04/09/2020 09:56:05 AM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 40, in main
    runner.test()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 310, in test
    A_tmp = model(input_dict)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 496, in forward
    A[ii, :num_nodes[ii], :num_nodes[ii]] for ii in range(batch_size)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 496, in <listcomp>
    A[ii, :num_nodes[ii], :num_nodes[ii]] for ii in range(batch_size)
TypeError: tuple indices must be integers or slices, not tuple

