INFO  | 04/09/2020 11:51:31 AM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-09-11-51-31_13432\log_exp_13432.txt
INFO  | 04/09/2020 11:51:31 AM | File run_exp.py           | Line 27    | Exp instance id = 13432
INFO  | 04/09/2020 11:51:31 AM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/09/2020 11:51:31 AM | File run_exp.py           | Line 29    | Config =
INFO  | 04/09/2020 11:51:31 AM | File gran_runner.py       | Line 139   | Train/val/test = 8/2/2
INFO  | 04/09/2020 11:51:31 AM | File gran_runner.py       | Line 152   | No Edges vs. Edges in training set = 2.0
INFO  | 04/09/2020 11:51:35 AM | File gran_runner.py       | Line 333   | Average test time per mini-batch = 0.5260443687438965
ERROR | 04/09/2020 11:51:35 AM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 40, in main
    runner.test()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 357, in test
    vis_graphs += [CGs[0]]
IndexError: list index out of range

